[package]
name = "wasi-crypto-guest"
version = "0.1.3"
authors = ["Frank Denis <github@pureftpd.org>"]
edition = "2018"
publish = false
description = "Example WASI-Crypto guest bindings for Rust"
license-file = "LICENSE"

[dependencies]
num_enum = "0.5.7"
wycheproof = "0.5.0"
