cargo-features = ["per-package-target"]

[package]
name = "wasi-crypto-guest"
version = "0.1.1"
authors = ["Frank Denis <github@pureftpd.org>"]
edition = "2018"
publish = false
forced-target = "wasm32-wasi"

[dependencies]
num_enum = "0.5"
